name: CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-docker:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Backend image
      uses: docker/build-push-action@v4
      with:
        context: ./dlp-system/backend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dlp-backend:latest

    - name: Build and push Frontend image
      uses: docker/build-push-action@v4
      with:
        context: ./dlp-system/frontend
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/dlp-frontend:latest
